from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src" / "assets" / "images"
OPTIMIZED_DIR = ROOT / "src" / "assets" / "optimized"
DATA_DIR = ROOT / "src" / "data"


@dataclass(frozen=True)
class VariantConfig:
    name: str
    output_dir: Path
    max_size: int
    quality: int


HERO_VARIANT = VariantConfig(
    name="hero",
    output_dir=OPTIMIZED_DIR / "hero",
    max_size=1440,
    quality=82,
)

ABOUT_VARIANT = VariantConfig(
    name="about",
    output_dir=OPTIMIZED_DIR / "about",
    max_size=960,
    quality=82,
)

GALLERY_THUMB_VARIANT = VariantConfig(
    name="gallery-thumb",
    output_dir=OPTIMIZED_DIR / "gallery" / "thumb",
    max_size=640,
    quality=72,
)

GALLERY_LIGHTBOX_VARIANT = VariantConfig(
    name="gallery-lightbox",
    output_dir=OPTIMIZED_DIR / "gallery" / "lightbox",
    max_size=1600,
    quality=80,
)

HERO_IMAGE_ID = "005"
ABOUT_IMAGE_ID = "025"


def iter_source_images() -> list[Path]:
    image_paths = [
        *SOURCE_DIR.glob("*.jpg"),
        *SOURCE_DIR.glob("*.jpeg"),
        *SOURCE_DIR.glob("*.png"),
    ]
    return sorted(image_paths, key=lambda path: path.stem)


def resize_to_webp(source_path: Path, variant: VariantConfig) -> tuple[Path, int, int]:
    output_path = variant.output_dir / f"{source_path.stem}.webp"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with Image.open(source_path) as image:
        image = ImageOps.exif_transpose(image)

        has_alpha = "A" in image.getbands()
        target_mode = "RGBA" if has_alpha else "RGB"
        if image.mode != target_mode:
            image = image.convert(target_mode)

        image.thumbnail((variant.max_size, variant.max_size), Image.Resampling.LANCZOS)
        width, height = image.size
        image.save(
            output_path,
            format="WEBP",
            quality=variant.quality,
            method=6,
        )

    return output_path, width, height


def write_gallery_module(entries: list[dict[str, int | str]]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    output_path = DATA_DIR / "galleryImages.js"

    import_lines: list[str] = []
    entry_lines: list[str] = []

    for entry in entries:
        image_id = entry["id"]
        import_lines.append(
            f'import galleryThumb{image_id} from "@/assets/optimized/gallery/thumb/{image_id}.webp";'
        )
        import_lines.append(
            f'import galleryLightbox{image_id} from "@/assets/optimized/gallery/lightbox/{image_id}.webp";'
        )

        entry_lines.extend(
            [
                "  {",
                f'    id: "{image_id}",',
                f"    thumbSrc: galleryThumb{image_id},",
                f"    thumbWidth: {entry['thumb_width']},",
                f"    thumbHeight: {entry['thumb_height']},",
                f"    lightboxSrc: galleryLightbox{image_id},",
                f"    lightboxWidth: {entry['lightbox_width']},",
                f"    lightboxHeight: {entry['lightbox_height']},",
                "  },",
            ]
        )

    module_lines = [
        "// This file is generated by scripts/generate_optimized_images.py",
        *import_lines,
        "",
        "export const galleryImages = [",
        *entry_lines,
        "];",
        "",
    ]

    output_path.write_text("\n".join(module_lines), encoding="utf-8")


def main() -> None:
    gallery_entries: list[dict[str, int | str]] = []

    for source_path in iter_source_images():
        image_id = source_path.stem

        _, thumb_width, thumb_height = resize_to_webp(source_path, GALLERY_THUMB_VARIANT)
        _, lightbox_width, lightbox_height = resize_to_webp(
            source_path, GALLERY_LIGHTBOX_VARIANT
        )

        gallery_entries.append(
            {
                "id": image_id,
                "thumb_width": thumb_width,
                "thumb_height": thumb_height,
                "lightbox_width": lightbox_width,
                "lightbox_height": lightbox_height,
            }
        )

        if image_id == HERO_IMAGE_ID:
            resize_to_webp(source_path, HERO_VARIANT)

        if image_id == ABOUT_IMAGE_ID:
            resize_to_webp(source_path, ABOUT_VARIANT)

    write_gallery_module(gallery_entries)


if __name__ == "__main__":
    main()
